# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
- openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
- bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
    - bespalov0928@smtp.ru
    on_success: never # default: change
    on_failure: always # default: always
env:
  global:
  - CODECOV_TOKEN="4577735a-620b-47db-8790-18555bd85a99"